"""crear tablas notificaciones

Revision ID: 4159033c2e87
Revises: 
Create Date: 2026-03-25 14:35:05.448455

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '4159033c2e87'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_envio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('notificacion_id', sa.Integer(), nullable=False),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('respuesta', sa.Text(), nullable=True),
    sa.Column('intentado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_envio_id'), 'log_envio', ['id'], unique=False)
    op.create_index(op.f('ix_log_envio_notificacion_id'), 'log_envio', ['notificacion_id'], unique=False)
    op.create_table('notificacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('dispositivo_id', sa.Integer(), nullable=False),
    sa.Column('id_logico', sa.String(length=50), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('severidad', sa.String(length=20), nullable=False),
    sa.Column('canal', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('creada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('enviada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('leida', sa.Boolean(), nullable=True),
    sa.Column('origen_evento', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificacion_dispositivo_id'), 'notificacion', ['dispositivo_id'], unique=False)
    op.create_index(op.f('ix_notificacion_id'), 'notificacion', ['id'], unique=False)
    op.create_index(op.f('ix_notificacion_id_logico'), 'notificacion', ['id_logico'], unique=False)
    op.create_table('preferencia_notificacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('canal_preferido', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('alertas_criticas', sa.Boolean(), nullable=True),
    sa.Column('alertas_altas', sa.Boolean(), nullable=True),
    sa.Column('alertas_medias', sa.Boolean(), nullable=True),
    sa.Column('alertas_bajas', sa.Boolean(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_preferencia_notificacion_id'), 'preferencia_notificacion', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_preferencia_notificacion_id'), table_name='preferencia_notificacion')
    op.drop_table('preferencia_notificacion')
    op.drop_index(op.f('ix_notificacion_id_logico'), table_name='notificacion')
    op.drop_index(op.f('ix_notificacion_id'), table_name='notificacion')
    op.drop_index(op.f('ix_notificacion_dispositivo_id'), table_name='notificacion')
    op.drop_table('notificacion')
    op.drop_index(op.f('ix_log_envio_notificacion_id'), table_name='log_envio')
    op.drop_index(op.f('ix_log_envio_id'), table_name='log_envio')
    op.drop_table('log_envio')
    # ### end Alembic commands ###