"""crear tablas ml

Revision ID: fa0d2bd49a2c
Revises: 
Create Date: 2026-04-02 16:16:13.059501

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'fa0d2bd49a2c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial_metrica',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_logico', sa.String(length=50), nullable=False),
    sa.Column('parcela_id', sa.Integer(), nullable=True),
    sa.Column('tipo_metrica', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('registrado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_metrica_id'), 'historial_metrica', ['id'], unique=False)
    op.create_index(op.f('ix_historial_metrica_id_logico'), 'historial_metrica', ['id_logico'], unique=False)
    op.create_index(op.f('ix_historial_metrica_parcela_id'), 'historial_metrica', ['parcela_id'], unique=False)
    op.create_table('modelo_registro',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('variable_target', sa.String(length=100), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('metricas', sa.JSON(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('registrado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modelo_registro_id'), 'modelo_registro', ['id'], unique=False)
    op.create_table('solicitud_prediccion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('modelo_id', sa.Integer(), nullable=False),
    sa.Column('parcela_id', sa.Integer(), nullable=True),
    sa.Column('id_logico', sa.String(length=50), nullable=True),
    sa.Column('tipo_prediccion', sa.String(length=50), nullable=False),
    sa.Column('datos_entrada', sa.JSON(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('solicitado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelo_registro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitud_prediccion_id'), 'solicitud_prediccion', ['id'], unique=False)
    op.create_table('resultado_prediccion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('valor_predicho', sa.Float(), nullable=False),
    sa.Column('confianza', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(length=30), nullable=True),
    sa.Column('explicacion', sa.Text(), nullable=True),
    sa.Column('datos_salida', sa.JSON(), nullable=True),
    sa.Column('generado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitud_prediccion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resultado_prediccion_id'), 'resultado_prediccion', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resultado_prediccion_id'), table_name='resultado_prediccion')
    op.drop_table('resultado_prediccion')
    op.drop_index(op.f('ix_solicitud_prediccion_id'), table_name='solicitud_prediccion')
    op.drop_table('solicitud_prediccion')
    op.drop_index(op.f('ix_modelo_registro_id'), table_name='modelo_registro')
    op.drop_table('modelo_registro')
    op.drop_index(op.f('ix_historial_metrica_parcela_id'), table_name='historial_metrica')
    op.drop_index(op.f('ix_historial_metrica_id_logico'), table_name='historial_metrica')
    op.drop_index(op.f('ix_historial_metrica_id'), table_name='historial_metrica')
    op.drop_table('historial_metrica')
    # ### end Alembic commands ###