services:

  nginx:
    image: nginx:alpine
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - servicio-auth
      - servicio-dispositivos
      - servicio-ingesta
      - servicio-procesamiento
      - servicio-notificaciones
      - servicio-parcelas
      - servicio-ml
      - servicio-recomendaciones
    restart: on-failure

  servicio-auth:
    build: ./servicio_auth
    expose:
      - "8008"
    environment:
      APP_ENV: production
      DATABASE_URL: postgresql://postgres:1234@postgres-auth:5432/auth_db
      JWT_SECRET: ${JWT_SECRET}
      REFRESH_SECRET: ${REFRESH_SECRET}
      JWT_ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
      REFRESH_TOKEN_EXPIRE_DAYS: 7
    depends_on:
      postgres-auth:
        condition: service_healthy
    restart: on-failure

  servicio-dispositivos:
    build: ./servicio_dispositivos
    expose:
      - "8001"
    environment:
      APP_ENV: production
      DATABASE_URL: postgresql://postgres:1234@postgres-dispositivos:5432/device_db
      BROKER_URL: kafka:9092
      JWT_SECRET: ${JWT_SECRET}
      REFRESH_SECRET: ${REFRESH_SECRET}
    depends_on:
      postgres-dispositivos:
        condition: service_healthy
      kafka:
        condition: service_started
    restart: on-failure

  servicio-ingesta:
    build: ./servicio_ingesta
    expose:
      - "8002"
    environment:
      APP_ENV: production
      DATABASE_URL: postgresql://postgres:1234@postgres-ingesta:5432/ingesta_db
      BROKER_URL: kafka:9092
      DEVICE_SERVICE_URL: http://servicio-dispositivos:8001
      JWT_SECRET: ${JWT_SECRET}
      REFRESH_SECRET: ${REFRESH_SECRET}
    depends_on:
      postgres-ingesta:
        condition: service_healthy
      kafka:
        condition: service_started
    restart: on-failure

  servicio-procesamiento:
    build: ./servicio_procesamiento
    expose:
      - "8003"
    environment:
      APP_ENV: production
      DATABASE_URL: postgresql://postgres:1234@postgres-procesamiento:5432/procesamiento_db
      BROKER_URL: kafka:9092
      KAFKA_GROUP_ID: stream-processor-group
      DEVICE_SERVICE_URL: http://servicio-dispositivos:8001
      INGESTA_SERVICE_URL: http://servicio-ingesta:8002
      JWT_SECRET: ${JWT_SECRET}
      REFRESH_SECRET: ${REFRESH_SECRET}
    depends_on:
      postgres-procesamiento:
        condition: service_healthy
      kafka:
        condition: service_started
    restart: on-failure

  servicio-notificaciones:
    build: ./servicio_notificaciones
    expose:
      - "8004"
    environment:
      APP_ENV: production
      DATABASE_URL: postgresql://postgres:1234@postgres-notificaciones:5432/notificaciones_db
      BROKER_URL: kafka:9092
      KAFKA_GROUP_ID: notification-service-group
      DEVICE_SERVICE_URL: http://servicio-dispositivos:8001
      AUTH_SERVICE_URL: http://servicio-auth:8008
      JWT_SECRET: ${JWT_SECRET}
      REFRESH_SECRET: ${REFRESH_SECRET}
      GMAIL_USER: axben888@gmail.com
      GMAIL_PASSWORD: ayow tvzx azgp rnmi
      GMAIL_FROM: AgriSense <axben888@gmail.com>
    depends_on:
      postgres-notificaciones:
        condition: service_healthy
      kafka:
        condition: service_started
    restart: on-failure

  servicio-parcelas:
    build: ./servicio_parcelas
    expose:
      - "8005"
    environment:
      APP_ENV: production
      DATABASE_URL: postgresql://postgres:1234@postgres-parcelas:5432/parcelas_db
      DEVICE_SERVICE_URL: http://servicio-dispositivos:8001
      JWT_SECRET: ${JWT_SECRET}
      REFRESH_SECRET: ${REFRESH_SECRET}
    depends_on:
      postgres-parcelas:
        condition: service_healthy
    restart: on-failure

  servicio-ml:
    build: ./servicio_ml
    expose:
      - "8006"
    environment:
      APP_ENV: production
      DATABASE_URL: postgresql://postgres:1234@postgres-ml:5432/ml_db
      DEVICE_SERVICE_URL: http://servicio-dispositivos:8001
      INGESTA_SERVICE_URL: http://servicio-ingesta:8002
      PARCELAS_SERVICE_URL: http://servicio-parcelas:8005
      JWT_SECRET: ${JWT_SECRET}
      REFRESH_SECRET: ${REFRESH_SECRET}
    depends_on:
      postgres-ml:
        condition: service_healthy
    restart: on-failure

  servicio-recomendaciones:
    build: ./servicio_recomendaciones
    expose:
      - "8007"
    environment:
      APP_ENV: production
      DATABASE_URL: postgresql://postgres:1234@postgres-recomendaciones:5432/recomendaciones_db
      DEVICE_SERVICE_URL: http://servicio-dispositivos:8001
      INGESTA_SERVICE_URL: http://servicio-ingesta:8002
      PROCESAMIENTO_SERVICE_URL: http://servicio-procesamiento:8003
      PARCELAS_SERVICE_URL: http://servicio-parcelas:8005
      ML_SERVICE_URL: http://servicio-ml:8006
      JWT_SECRET: ${JWT_SECRET}
      REFRESH_SECRET: ${REFRESH_SECRET}
    depends_on:
      postgres-recomendaciones:
        condition: service_healthy
      servicio-ml:
        condition: service_started
    restart: on-failure

  postgres-auth:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: auth_db
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-dispositivos:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: device_db
    volumes:
      - postgres_dispositivos_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-ingesta:
    image: timescale/timescaledb:latest-pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: ingesta_db
    volumes:
      - postgres_ingesta_data:/var/lib/postgresql/data
      - ./servicio_ingesta/scripts/init_timescale.sql:/docker-entrypoint-initdb.d/init_timescale.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-procesamiento:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: procesamiento_db
    volumes:
      - postgres_procesamiento_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-notificaciones:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: notificaciones_db
    volumes:
      - postgres_notificaciones_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-parcelas:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: parcelas_db
    volumes:
      - postgres_parcelas_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-ml:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: ml_db
    volumes:
      - postgres_ml_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-recomendaciones:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: recomendaciones_db
    volumes:
      - postgres_recomendaciones_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on: [zookeeper]
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  postgres_auth_data:
  postgres_dispositivos_data:
  postgres_ingesta_data:
  postgres_procesamiento_data:
  postgres_notificaciones_data:
  postgres_parcelas_data:
  postgres_ml_data:
  postgres_recomendaciones_data: