services:
  - type: web
    name: agrisense-auth
    runtime: docker
    dockerfilePath: ./servicio_auth/Dockerfile
    dockerContext: ./servicio_auth
    plan: free
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_5BAsWIO1XaYj@ep-flat-shape-aj8qjbrl.c-3.us-east-2.aws.neon.tech/neondb?sslmode=require
      - key: JWT_SECRET
        value: agrisense_jwt_secret_2026_prod
      - key: REFRESH_SECRET
        value: agrisense_refresh_secret_2026_prod
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "60"
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: "7"
      - key: APP_ENV
        value: production

  - type: web
    name: agrisense-dispositivos
    runtime: docker
    dockerfilePath: ./servicio_dispositivos/Dockerfile
    dockerContext: ./servicio_dispositivos
    plan: free
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_r3VYgcA8RNEu@ep-orange-voice-ajg3v76p-pooler.c-3.us-east-2.aws.neon.tech/neondb?sslmode=require
      - key: JWT_SECRET
        value: agrisense_jwt_secret_2026_prod
      - key: REFRESH_SECRET
        value: agrisense_refresh_secret_2026_prod
      - key: APP_ENV
        value: production
      - key: BROKER_URL
        value: ""

  - type: web
    name: agrisense-ingesta
    runtime: docker
    dockerfilePath: ./servicio_ingesta/Dockerfile
    dockerContext: ./servicio_ingesta
    plan: free
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_GBo1Aagq9lEu@ep-ancient-hat-aejqk0zi-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require
      - key: JWT_SECRET
        value: agrisense_jwt_secret_2026_prod
      - key: REFRESH_SECRET
        value: agrisense_refresh_secret_2026_prod
      - key: DEVICE_SERVICE_URL
        value: https://agrisense-dispositivos.onrender.com
      - key: APP_ENV
        value: production
      - key: BROKER_URL
        value: ""

  - type: web
    name: agrisense-procesamiento
    runtime: docker
    dockerfilePath: ./servicio_procesamiento/Dockerfile
    dockerContext: ./servicio_procesamiento
    plan: free
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_IeLUqMfhEb35@ep-frosty-salad-aeeh6eyi-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require
      - key: JWT_SECRET
        value: agrisense_jwt_secret_2026_prod
      - key: REFRESH_SECRET
        value: agrisense_refresh_secret_2026_prod
      - key: DEVICE_SERVICE_URL
        value: https://agrisense-dispositivos.onrender.com
      - key: INGESTA_SERVICE_URL
        value: https://agrisense-ingesta.onrender.com
      - key: APP_ENV
        value: production
      - key: BROKER_URL
        value: ""

  - type: web
    name: agrisense-notificaciones
    runtime: docker
    dockerfilePath: ./servicio_notificaciones/Dockerfile
    dockerContext: ./servicio_notificaciones
    plan: free
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_6Mg0xDAjXcKe@ep-wild-surf-ajd42p5q-pooler.c-3.us-east-2.aws.neon.tech/neondb?sslmode=require
      - key: JWT_SECRET
        value: agrisense_jwt_secret_2026_prod
      - key: REFRESH_SECRET
        value: agrisense_refresh_secret_2026_prod
      - key: AUTH_SERVICE_URL
        value: https://agrisense-auth.onrender.com
      - key: DEVICE_SERVICE_URL
        value: https://agrisense-dispositivos.onrender.com
      - key: GMAIL_USER
        value: axben888@gmail.com
      - key: GMAIL_PASSWORD
        value: ayow tvzx azgp rnmi
      - key: GMAIL_FROM
        value: AgriSense <axben888@gmail.com>
      - key: APP_ENV
        value: production
      - key: BROKER_URL
        value: ""

  - type: web
    name: agrisense-parcelas
    runtime: docker
    dockerfilePath: ./servicio_parcelas/Dockerfile
    dockerContext: ./servicio_parcelas
    plan: free
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_UM3WJit8lKRD@ep-raspy-river-ajgwqad1-pooler.c-3.us-east-2.aws.neon.tech/neondb?sslmode=require
      - key: JWT_SECRET
        value: agrisense_jwt_secret_2026_prod
      - key: REFRESH_SECRET
        value: agrisense_refresh_secret_2026_prod
      - key: DEVICE_SERVICE_URL
        value: https://agrisense-dispositivos.onrender.com
      - key: APP_ENV
        value: production
      - key: BROKER_URL
        value: ""

  - type: web
    name: agrisense-ml
    runtime: docker
    dockerfilePath: ./servicio_ml/Dockerfile
    dockerContext: ./servicio_ml
    plan: free
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_4VuSspar2gmB@ep-odd-thunder-aemfljpy-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require
      - key: JWT_SECRET
        value: agrisense_jwt_secret_2026_prod
      - key: REFRESH_SECRET
        value: agrisense_refresh_secret_2026_prod
      - key: DEVICE_SERVICE_URL
        value: https://agrisense-dispositivos.onrender.com
      - key: INGESTA_SERVICE_URL
        value: https://agrisense-ingesta.onrender.com
      - key: APP_ENV
        value: production
      - key: BROKER_URL
        value: ""

  - type: web
    name: agrisense-recomendaciones
    runtime: docker
    dockerfilePath: ./servicio_recomendaciones/Dockerfile
    dockerContext: ./servicio_recomendaciones
    plan: free
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_ykcrRm6gsIT7@ep-little-darkness-ajnmrayp-pooler.c-3.us-east-2.aws.neon.tech/neondb?sslmode=require
      - key: JWT_SECRET
        value: agrisense_jwt_secret_2026_prod
      - key: REFRESH_SECRET
        value: agrisense_refresh_secret_2026_prod
      - key: DEVICE_SERVICE_URL
        value: https://agrisense-dispositivos.onrender.com
      - key: INGESTA_SERVICE_URL
        value: https://agrisense-ingesta.onrender.com
      - key: PROCESAMIENTO_SERVICE_URL
        value: https://agrisense-procesamiento.onrender.com
      - key: APP_ENV
        value: production
      - key: BROKER_URL
        value: ""

  - type: web
    name: agrisense-gateway
    runtime: docker
    dockerfilePath: ./nginx/Dockerfile
    dockerContext: ./nginx
    plan: free
    envVars:
      - key: APP_ENV
        value: production