version: "3.9"

services:

  notification-service:
    build: .
    ports:
      - "8004:8004"
    environment:
      APP_ENV: development
      DATABASE_URL: postgresql://postgres:1234@postgres:5432/notificaciones_db
      BROKER_URL: kafka:9092
      KAFKA_GROUP_ID: notification-service-group
      DEVICE_SERVICE_URL: http://servicio-dispositivos:8001
      JWT_SECRET: local-secret-dev
      REFRESH_SECRET: local-refresh-dev
      AUTH_SERVICE_URL: http://servicio-auth:8008
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    restart: on-failure

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: notificaciones_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_notificaciones_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on: [zookeeper]
    ports:
      - "9095:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  postgres_notificaciones_data: