"""crear tablas parcelas

Revision ID: 6fe79a4b3ebc
Revises: 
Create Date: 2026-03-30 10:17:26.317272

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '6fe79a4b3ebc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parcela',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('area_hectareas', sa.Float(), nullable=False),
    sa.Column('tipo_suelo', sa.String(length=50), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('altitud_msnm', sa.Float(), nullable=True),
    sa.Column('departamento', sa.String(length=100), nullable=True),
    sa.Column('municipio', sa.String(length=100), nullable=True),
    sa.Column('vereda', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('propietario_id', sa.Integer(), nullable=True),
    sa.Column('creada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizada_en', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcela_id'), 'parcela', ['id'], unique=False)
    op.create_table('tipo_cultivo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('temporada', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_tipo_cultivo_id'), 'tipo_cultivo', ['id'], unique=False)
    op.create_table('historial_cultivo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parcela_id', sa.Integer(), nullable=False),
    sa.Column('tipo_cultivo_id', sa.Integer(), nullable=False),
    sa.Column('fecha_siembra', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_cosecha', sa.DateTime(timezone=True), nullable=True),
    sa.Column('etapa_fenologica', sa.String(length=50), nullable=True),
    sa.Column('rendimiento_kg', sa.Float(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcela.id'], ),
    sa.ForeignKeyConstraint(['tipo_cultivo_id'], ['tipo_cultivo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_cultivo_id'), 'historial_cultivo', ['id'], unique=False)
    op.create_index(op.f('ix_historial_cultivo_parcela_id'), 'historial_cultivo', ['parcela_id'], unique=False)
    op.create_table('parcela_sensor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parcela_id', sa.Integer(), nullable=False),
    sa.Column('dispositivo_id', sa.Integer(), nullable=False),
    sa.Column('id_logico', sa.String(length=50), nullable=False),
    sa.Column('fecha_instalacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcela.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcela_sensor_id'), 'parcela_sensor', ['id'], unique=False)
    op.create_index(op.f('ix_parcela_sensor_id_logico'), 'parcela_sensor', ['id_logico'], unique=False)
    op.create_index(op.f('ix_parcela_sensor_parcela_id'), 'parcela_sensor', ['parcela_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parcela_sensor_parcela_id'), table_name='parcela_sensor')
    op.drop_index(op.f('ix_parcela_sensor_id_logico'), table_name='parcela_sensor')
    op.drop_index(op.f('ix_parcela_sensor_id'), table_name='parcela_sensor')
    op.drop_table('parcela_sensor')
    op.drop_index(op.f('ix_historial_cultivo_parcela_id'), table_name='historial_cultivo')
    op.drop_index(op.f('ix_historial_cultivo_id'), table_name='historial_cultivo')
    op.drop_table('historial_cultivo')
    op.drop_index(op.f('ix_tipo_cultivo_id'), table_name='tipo_cultivo')
    op.drop_table('tipo_cultivo')
    op.drop_index(op.f('ix_parcela_id'), table_name='parcela')
    op.drop_table('parcela')
    # ### end Alembic commands ###