"""crear tablas procesamiento

Revision ID: 2a4059122f46
Revises: 
Create Date: 2026-03-25 12:09:40.062124

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '2a4059122f46'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerta_stream',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dispositivo_id', sa.Integer(), nullable=False),
    sa.Column('id_logico', sa.String(length=50), nullable=False),
    sa.Column('tipo_metrica', sa.String(length=50), nullable=False),
    sa.Column('valor_detectado', sa.Float(), nullable=False),
    sa.Column('condicion', sa.String(length=255), nullable=False),
    sa.Column('severidad', sa.String(length=20), nullable=False),
    sa.Column('tipo_alerta', sa.String(length=50), nullable=False),
    sa.Column('generada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('notificada', sa.Boolean(), nullable=True),
    sa.Column('evento_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerta_stream_dispositivo_id'), 'alerta_stream', ['dispositivo_id'], unique=False)
    op.create_index(op.f('ix_alerta_stream_id'), 'alerta_stream', ['id'], unique=False)
    op.create_index(op.f('ix_alerta_stream_id_logico'), 'alerta_stream', ['id_logico'], unique=False)
    op.create_table('evento_procesado',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dispositivo_id', sa.Integer(), nullable=False),
    sa.Column('id_logico', sa.String(length=50), nullable=False),
    sa.Column('tipo_metrica', sa.String(length=50), nullable=False),
    sa.Column('valor_metrica', sa.Float(), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=True),
    sa.Column('timestamp_lectura', sa.DateTime(timezone=True), nullable=False),
    sa.Column('procesado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('tiene_alerta', sa.Boolean(), nullable=True),
    sa.Column('topic_origen', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evento_procesado_dispositivo_id'), 'evento_procesado', ['dispositivo_id'], unique=False)
    op.create_index(op.f('ix_evento_procesado_id'), 'evento_procesado', ['id'], unique=False)
    op.create_index(op.f('ix_evento_procesado_id_logico'), 'evento_procesado', ['id_logico'], unique=False)
    op.create_table('regla_aplicada',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_regla', sa.String(length=100), nullable=False),
    sa.Column('dispositivo_id', sa.Integer(), nullable=False),
    sa.Column('id_logico', sa.String(length=50), nullable=False),
    sa.Column('tipo_metrica', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('resultado', sa.String(length=20), nullable=False),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('aplicada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regla_aplicada_id'), 'regla_aplicada', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_regla_aplicada_id'), table_name='regla_aplicada')
    op.drop_table('regla_aplicada')
    op.drop_index(op.f('ix_evento_procesado_id_logico'), table_name='evento_procesado')
    op.drop_index(op.f('ix_evento_procesado_id'), table_name='evento_procesado')
    op.drop_index(op.f('ix_evento_procesado_dispositivo_id'), table_name='evento_procesado')
    op.drop_table('evento_procesado')
    op.drop_index(op.f('ix_alerta_stream_id_logico'), table_name='alerta_stream')
    op.drop_index(op.f('ix_alerta_stream_id'), table_name='alerta_stream')
    op.drop_index(op.f('ix_alerta_stream_dispositivo_id'), table_name='alerta_stream')
    op.drop_table('alerta_stream')
    # ### end Alembic commands ###