global:
  scrape_interval:     30s
  evaluation_interval: 15s
  external_labels:
    monitor: 'agrisense'

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'agrisense-auth'
    static_configs:
      - targets: ['agrisense-auth.onrender.com']
    scheme: https
    metrics_path: '/metrics'
    tls_config:
      insecure_skip_verify: true

  - job_name: 'agrisense-dispositivos'
    static_configs:
      - targets: ['agrisense-dispositivos.onrender.com']
    scheme: https
    metrics_path: '/metrics'
    tls_config:
      insecure_skip_verify: true

  - job_name: 'agrisense-ingesta'
    static_configs:
      - targets: ['agrisense-ingesta.onrender.com']
    scheme: https
    metrics_path: '/metrics'
    tls_config:
      insecure_skip_verify: true

  - job_name: 'agrisense-procesamiento'
    static_configs:
      - targets: ['agrisense-procesamiento.onrender.com']
    scheme: https
    metrics_path: '/metrics'
    tls_config:
      insecure_skip_verify: true

  - job_name: 'agrisense-notificaciones'
    static_configs:
      - targets: ['agrisense-notificaciones.onrender.com']
    scheme: https
    metrics_path: '/metrics'
    tls_config:
      insecure_skip_verify: true

  - job_name: 'agrisense-parcelas'
    static_configs:
      - targets: ['agrisense-parcelas.onrender.com']
    scheme: https
    metrics_path: '/metrics'
    tls_config:
      insecure_skip_verify: true

  - job_name: 'agrisense-ml'
    static_configs:
      - targets: ['agrisense-ml.onrender.com']
    scheme: https
    metrics_path: '/metrics'
    tls_config:
      insecure_skip_verify: true

  - job_name: 'agrisense-recomendaciones'
    static_configs:
      - targets: ['agrisense-recomendaciones.onrender.com']
    scheme: https
    metrics_path: '/metrics'
    tls_config:
      insecure_skip_verify: true

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']