"""crear tablas ingesta

Revision ID: 903c8157fe4e
Revises: 
Create Date: 2026-03-24 21:53:45.461655

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '903c8157fe4e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerta_generada',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dispositivo_id', sa.Integer(), nullable=False),
    sa.Column('id_logico', sa.String(length=50), nullable=False),
    sa.Column('tipo_metrica', sa.String(length=50), nullable=False),
    sa.Column('valor_detectado', sa.Float(), nullable=False),
    sa.Column('condicion', sa.String(length=255), nullable=False),
    sa.Column('severidad', sa.String(length=20), nullable=True),
    sa.Column('generada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('enviada', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerta_generada_dispositivo_id'), 'alerta_generada', ['dispositivo_id'], unique=False)
    op.create_index(op.f('ix_alerta_generada_id'), 'alerta_generada', ['id'], unique=False)
    op.create_table('lote_ingesta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_origen', sa.String(length=10), nullable=False),
    sa.Column('recibido_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('total_registros', sa.Integer(), nullable=True),
    sa.Column('registros_validos', sa.Integer(), nullable=True),
    sa.Column('registros_invalidos', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lote_ingesta_id'), 'lote_ingesta', ['id'], unique=False)
    op.create_table('error_ingesta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.Column('payload_raw', sa.Text(), nullable=True),
    sa.Column('razon_error', sa.String(length=255), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lote_id'], ['lote_ingesta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_ingesta_id'), 'error_ingesta', ['id'], unique=False)
    op.create_table('lectura_sensor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dispositivo_id', sa.Integer(), nullable=False),
    sa.Column('id_logico', sa.String(length=50), nullable=False),
    sa.Column('tipo_metrica', sa.String(length=50), nullable=False),
    sa.Column('valor_metrica', sa.Float(), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=True),
    sa.Column('timestamp_lectura', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recibido_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('bandera_calidad', sa.String(length=10), nullable=True),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lote_id'], ['lote_ingesta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lectura_sensor_dispositivo_id'), 'lectura_sensor', ['dispositivo_id'], unique=False)
    op.create_index(op.f('ix_lectura_sensor_id'), 'lectura_sensor', ['id'], unique=False)
    op.create_index(op.f('ix_lectura_sensor_id_logico'), 'lectura_sensor', ['id_logico'], unique=False)
    op.create_index(op.f('ix_lectura_sensor_timestamp_lectura'), 'lectura_sensor', ['timestamp_lectura'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lectura_sensor_timestamp_lectura'), table_name='lectura_sensor')
    op.drop_index(op.f('ix_lectura_sensor_id_logico'), table_name='lectura_sensor')
    op.drop_index(op.f('ix_lectura_sensor_id'), table_name='lectura_sensor')
    op.drop_index(op.f('ix_lectura_sensor_dispositivo_id'), table_name='lectura_sensor')
    op.drop_table('lectura_sensor')
    op.drop_index(op.f('ix_error_ingesta_id'), table_name='error_ingesta')
    op.drop_table('error_ingesta')
    op.drop_index(op.f('ix_lote_ingesta_id'), table_name='lote_ingesta')
    op.drop_table('lote_ingesta')
    op.drop_index(op.f('ix_alerta_generada_id'), table_name='alerta_generada')
    op.drop_index(op.f('ix_alerta_generada_dispositivo_id'), table_name='alerta_generada')
    op.drop_table('alerta_generada')
    # ### end Alembic commands ###