"""agregar usuario_id a dispositivo

Revision ID: 16064b7455f7
Revises: 854fa1ed2737
Create Date: 2026-04-07 16:18:41.086690

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '16064b7455f7'
down_revision: Union[str, None] = '854fa1ed2737'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    op.add_column('dispositivo', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_dispositivo_usuario_id'), 'dispositivo', ['usuario_id'], unique=False)
    # Asignar datos existentes al admin (usuario_id=1)
    op.execute("UPDATE dispositivo SET usuario_id = 1 WHERE usuario_id IS NULL")
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dispositivo_usuario_id'), table_name='dispositivo')
    op.drop_column('dispositivo', 'usuario_id')
    # ### end Alembic commands ###