"""tablas en español con despliegues

Revision ID: 1a5b42f1efa1
Revises: 
Create Date: 2026-03-22 16:03:59.963911

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '1a5b42f1efa1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_dispositivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('unidad', sa.String(length=30), nullable=True),
    sa.Column('rango_minimo', sa.Float(), nullable=True),
    sa.Column('rango_maximo', sa.Float(), nullable=True),
    sa.Column('umbral_alerta', sa.String(length=100), nullable=True),
    sa.Column('tipo_pin', sa.String(length=50), nullable=True),
    sa.Column('metricas_permitidas', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_tipo_dispositivo_id'), 'tipo_dispositivo', ['id'], unique=False)
    op.create_table('dispositivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_dispositivo_id', sa.Integer(), nullable=False),
    sa.Column('id_logico', sa.String(length=50), nullable=False),
    sa.Column('numero_serial', sa.String(length=100), nullable=False),
    sa.Column('version_firmware', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('registrado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ultima_conexion', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("estado IN ('activo','inactivo','mantenimiento','averiado')", name='ck_dispositivo_estado'),
    sa.ForeignKeyConstraint(['tipo_dispositivo_id'], ['tipo_dispositivo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_logico'),
    sa.UniqueConstraint('numero_serial')
    )
    op.create_index(op.f('ix_dispositivo_id'), 'dispositivo', ['id'], unique=False)
    op.create_table('configuracion_dispositivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispositivo_id', sa.Integer(), nullable=False),
    sa.Column('intervalo_muestreo', sa.Integer(), nullable=True),
    sa.Column('protocolo_transmision', sa.String(length=10), nullable=True),
    sa.Column('umbral_bateria', sa.SmallInteger(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dispositivo_id'], ['dispositivo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dispositivo_id')
    )
    op.create_index(op.f('ix_configuracion_dispositivo_id'), 'configuracion_dispositivo', ['id'], unique=False)
    op.create_table('despliegue_dispositivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispositivo_id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.String(length=50), nullable=False),
    sa.Column('posicion', sa.String(length=100), nullable=True),
    sa.Column('instalado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('retirado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('motivo_retiro', sa.String(length=200), nullable=True),
    sa.Column('reemplazado_por', sa.Integer(), nullable=True),
    sa.CheckConstraint("estado IN ('activo','retirado','mantenimiento','averiado')", name='ck_despliegue_estado'),
    sa.ForeignKeyConstraint(['dispositivo_id'], ['dispositivo.id'], ),
    sa.ForeignKeyConstraint(['reemplazado_por'], ['dispositivo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_despliegue_dispositivo_id'), 'despliegue_dispositivo', ['id'], unique=False)
    op.create_table('historial_estado_dispositivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispositivo_id', sa.Integer(), nullable=False),
    sa.Column('estado_anterior', sa.String(length=20), nullable=True),
    sa.Column('estado_nuevo', sa.String(length=20), nullable=False),
    sa.Column('cambiado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['dispositivo_id'], ['dispositivo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_estado_dispositivo_id'), 'historial_estado_dispositivo', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historial_estado_dispositivo_id'), table_name='historial_estado_dispositivo')
    op.drop_table('historial_estado_dispositivo')
    op.drop_index(op.f('ix_despliegue_dispositivo_id'), table_name='despliegue_dispositivo')
    op.drop_table('despliegue_dispositivo')
    op.drop_index(op.f('ix_configuracion_dispositivo_id'), table_name='configuracion_dispositivo')
    op.drop_table('configuracion_dispositivo')
    op.drop_index(op.f('ix_dispositivo_id'), table_name='dispositivo')
    op.drop_table('dispositivo')
    op.drop_index(op.f('ix_tipo_dispositivo_id'), table_name='tipo_dispositivo')
    op.drop_table('tipo_dispositivo')
    # ### end Alembic commands ###