"""agregar limites y parcela a configuracion

Revision ID: 854fa1ed2737
Revises: 1a5b42f1efa1
Create Date: 2026-04-04 17:14:39.988582

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '854fa1ed2737'
down_revision: Union[str, None] = '1a5b42f1efa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuracion_dispositivo', sa.Column('limite_minimo', sa.Float(), nullable=True))
    op.add_column('configuracion_dispositivo', sa.Column('limite_maximo', sa.Float(), nullable=True))
    op.add_column('configuracion_dispositivo', sa.Column('parcela_id', sa.Integer(), nullable=True))
    op.add_column('configuracion_dispositivo', sa.Column('parcela_nombre', sa.String(length=100), nullable=True))
    op.add_column('configuracion_dispositivo', sa.Column('posicion_campo', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configuracion_dispositivo', 'posicion_campo')
    op.drop_column('configuracion_dispositivo', 'parcela_nombre')
    op.drop_column('configuracion_dispositivo', 'parcela_id')
    op.drop_column('configuracion_dispositivo', 'limite_maximo')
    op.drop_column('configuracion_dispositivo', 'limite_minimo')
    # ### end Alembic commands ###